name: Release pipeline

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.7 ]
        os: [ ubuntu-latest ]

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-
      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -U -r dev-requirements.txt
      
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release-${{ env.GITHUB_REF_SLUG }}

      - name: Release Code to Production
        run: databricks repos update --path=/Repos/Production/databricks-repos-ci-demo --branch=release-${{ env.GITHUB_REF_SLUG }}

      - name: Deploy the job
        run: |
          dbx deploy --no-rebuild --deployment-file=conf/production.json --no-package